### ISSUE TITLE
Add touch event support for mobile devices

### ISSUE THREAD

**Issue by muhammad-towfique-imam** [thelostword/timeline#11] opened 2024-09-15 10:39 UTC
Currently, TimeLine component works well on desktop devices using mouse interactions. However, to improve usability on mobile devices, support for touch events are required. This will allow users to interact with the timeline using touch gestures on smartphones and tablets.

## Proposed Changes
1. Add touch event listeners for `touchstart`, `touchmove`, and `touchend` events.
2. Implement touch-based dragging to move the timeline.
3. Ensure smooth performance on various mobile devices.

## Technical Details
- Modify the `TimeLine` class in `main.ts` to handle touch events.
- Implement new methods: `#onTouchStart`, `#onTouchMove`, and `#onTouchEnd`.

## Expected Behavior
- Users should be able to drag the timeline left and right using a single finger.
- The timeline should respond smoothly to touch gestures, providing a native-like experience on mobile devices.

**Comment by muhammad-towfique-imam** [comment] 2024-09-15 10:41
I have implemented this in my fork. Here is the link to test:
https://muhammad-towfique-imam.github.io/timeline/

**Comment by thelostword** [comment] 2024-09-16 03:08
This library happens to be missing mobile support，and your test link works great. Have you considered submitting a PR? I'd be more than happy to merge it. By the way, thank you for your fix of the 'Drag Functionality' Bug in Firefox. I learned a lot from it. I really appreciate your contribution!😊

**Comment by muhammad-towfique-imam** [comment] 2024-09-16 05:47
Thank you for your kind words! It's a great feeling to contribute to such a useful library.

Regarding mobile support, I would be happy to submit a PR. I have plans to implement a pinch-to-zoom feature for the scroll button functionality, but that can come a bit later.

Thank you again for the positive feedback and for maintaining this valuable library.

**Comment by thelostword** [comment] 2024-09-18 07:06
Hi, I’ve just added the pinch-to-zoom functionality https://github.com/thelostword/timeline/commit/4509f7a3b0e997b7c03ce75f4f0da11d15655ada. I tested it on the mobile version of Edge browser, and it seems to be working well. Test link: https://thelostword.github.io/timeline/. However, there are some details that might need optimization, such as dragging while performing the pinch-to-zoom gesture...

**Comment by muhammad-towfique-imam** [comment] 2024-09-18 09:02
Hi, Just did a quick test. The pinch-to-zoom seems to work well except for one case. When it hits the upper bound (1weeks) and lower bound(10ms), it stopps working. 

Regards

**Comment by thelostword** [comment] 2024-09-19 01:20
> Hi, Just did a quick test. The pinch-to-zoom seems to work well except for one case. When it hits the upper bound (1weeks) and lower bound(10ms), it stopps working.
> 
> Regards

Yes, I just fixed it. It was caused by poor judgment.

**Comment by muhammad-towfique-imam** [comment] 2024-09-19 07:57
Working great now. Do you have plans to release a new version with these changes?

**Comment by thelostword** [comment] 2024-09-19 08:34
> Working great now. Do you have plans to release a new version with these changes?

I will release it soon, and it will be version 5.

**Comment by thelostword** [comment] 2024-09-19 09:54
Just released a new version v5.0, which supports mobile devices. Additionally, some methods have been added that may be useful. If there are no other bugs, I will close this in a little while. Thank you for your great contribution to this feature.😊

Regards

**Comment by muhammad-towfique-imam** [comment] 2024-09-19 15:54
Tested version 5.0.0. You can close this issue as everything is working perfectly. 

BTW, appreciate your quick work in deploying these updates, @thelostword. Also your efforts to maintain this essential library and your openness to community input are truly commendable.

**Closed as completed** 2024-09-20 02:02 UTC
